### ISSUE TITLE
distiller is failing at merge_zoom_library_group_coolers 

### ISSUE THREAD

**Issue by nandankita** [mirnylab/distiller-nf#136]
At the step of cooler zoom where it combines all the libraries into one last library it fails giving me the following error:
` cooler zoomify         --nproc 8         --out hic-library.no_filter.1000.mcool     
    --resolutions 1000000,500000,250000,100000,50000,40000,25000,10000,5000,2000,1000         --balance    
      hic-library.no_filter.1000.cool

  INFO:cooler.reduce:Aggregating from 50000 to 250000.
  INFO:cooler.create:Creating cooler at "hic-library.1000.mcool::/resolutions/250000"
  INFO:cooler.create:Writing chroms
  INFO:cooler.create:Writing bins
..
..
INFO:cooler.reduce:90025598 100021284
  Traceback (most recent call last):
    File "/miniconda3/bin/cooler", line 11, in <module>
      sys.exit(cli())
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
      return self.main(*args, **kwargs)
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
      rv = self.invoke(ctx)
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
      return callback(*args, **kwargs)
    File "/miniconda3/lib/python3.6/site-packages/cooler/cli/zoomify.py", line 145, in zoomify
      agg=agg)
    File "/miniconda3/lib/python3.6/site-packages/cooler/reduce.py", line 700, in zoomify_cooler
      **kwargs
    File "/miniconda3/lib/python3.6/site-packages/cooler/reduce.py", line 598, in coarsen_cooler
      **kwargs)
    File "/miniconda3/lib/python3.6/site-packages/cooler/create/_create.py", line 565, in create
      file_path, target, meta.columns, iterable, h5opts, lock)
    File "/miniconda3/lib/python3.6/site-packages/cooler/create/_create.py", line 221, in write_pixels
      dset.resize((nnz + n,))
    File "/miniconda3/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 438, in resize
      self.id.set_extent(size)
    File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
    File "h5py/h5d.pyx", line 274, in h5py.h5d.DatasetID.set_extent
  ValueError: Unable to set extend dataset (dimension cannot exceed the existing maximal size (new: 4959926 max: 4953378))
`
For the same combination I can see that the following steps are done,
INFO:cooler.reduce:Aggregating from 1000 to 2000.
INFO:cooler.reduce:Aggregating from 1000 to 5000.
INFO:cooler.reduce:Aggregating from 5000 to 10000.
INFO:cooler.reduce:Aggregating from 5000 to 25000.
INFO:cooler.reduce:Aggregating from 10000 to 40000
INFO:cooler.reduce:Aggregating from 25000 to 50000.

I tried the same library without balancing and that also fails for the same error. Any suggestion, what can be wrong.

**Comment by golobor** [comment]
Summoning @nvictus to this thread

**Comment by mimakaev** [comment]
This is a known bug - we couldn't figure out why it appears. Restart usually help. We've been searching for a reproducible version of it, but it never materialized. 
@nandankita   did you try restarting? Is it reproducible? This is very valuable, because we will be able to add some debug flags perhaps. 
@golobor can we set retry=2 for making coolers?

**Comment by nandankita** [comment]
I have tried this twice, like remove the complete intermediates and work folder and start the pipeline from the beginning. But it still fails with the same error. I tried to zoom the individual merged cooler file separately but I encounter the same error again. I'll try to resume the pipeline now and will update how it goes.

**Comment by mimakaev** [comment]
If you tried zooming a file separately, and it failed, is it somehow
possible for us to have this file? It may help us track down a bug we've
been having for months.

**Comment by nvictus** [comment]
The error traceback you got makes me think it might not even be the strange nextflow hanging issue we've sporadically encountered. Either way, @nandankita if you can share the 1kb cooler it would help a lot.

**Comment by nandankita** [comment]
Shared the file via email.

**Comment by golobor** [comment]
@nandankita , the new release includes a new version of cooler. Could you please test it and see if it solves the issue?

**Comment by nandankita** [comment]
I have tested the new version, works well. Thank you!
