### ISSUE TITLE
Error while balancing

### ISSUE THREAD

**Issue by nandankita** [mirnylab/distiller-nf#89]
Hi Anton & Nezar,

I am keep on running into this balancing error while balancing step where it says,
ValueError:  operands could not be broadcast together with shapes (52876,) (52877,) 

Sergey has explained me about this error where it is due to one off reporting in cooler file.  Please let me know if this can be fixed. Following is the complete error I get:

`INFO:cooler:Writing indexes
  INFO:cooler:Writing info
  INFO:cooler:Done
  INFO:cooler:Balancing "test-HiC-R1.10000.cool"
  multiprocess.pool.RemoteTraceback: 
  """
  Traceback (most recent call last):
    File "/home/lib/miniconda3/lib/python3.6/site-packages/multiprocess/pool.py", line 119, in worker
      result = (True, func(*args, **kwds))
    File "/home/lib/miniconda3/lib/python3.6/site-packages/cooler/tools.py", line 51, in apply_pipeline
      data = func(chunk, data)
    File "/home/lib/miniconda3/lib/python3.6/site-packages/cooler/ice.py", line 59, in _marginalize
      + np.bincount(pixels['bin2_id'], weights=data, minlength=n)
  ValueError: operands could not be broadcast together with shapes (52876,) (52877,) 
  """
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/home/lib/miniconda3/bin/cooler", line 11, in <module>
      sys.exit(cli())
    File "/home/lib/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
      return self.main(*args, **kwargs)
    File "/home/lib/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
      rv = self.invoke(ctx)
    File "/home/lib/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/lib/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/lib/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
      return callback(*args, **kwargs)
    File "/home/lib/miniconda3/lib/python3.6/site-packages/cooler/cli/balance.py", line 184, in balance
      map=pool.imap_unordered)
    File "/home/lib/miniconda3/lib/python3.6/site-packages/cooler/ice.py", line 257, in iterative_correction
      .reduce(add, np.zeros(n_bins))
    File "/home/lib/miniconda3/lib/python3.6/site-packages/cooler/tools.py", line 241, in reduce
      return reduce(binop, iter(self.run()), init)
    File "/home/lib/miniconda3/lib/python3.6/site-packages/multiprocess/pool.py", line 695, in next
      raise value
  ValueError: operands could not be broadcast together with shapes (52876,) (52877,) `

**Comment by golobor** [comment]
this might be related to the two issues discovered by @sergpolly: (a) 1-based indexing in .pairs vs 0-based indexing in .cool and (b) semi-open vs closed intervals in .pairs. (b) is fixed, but wasn't pushed to distiller yet. @nvictus, do you know if (a) is fixed?

**Comment by sergpolly** [comment]
By looking at cooler commits, it doesn't seem like (a) is solved on the cooler side.. @nvictus ?
(b) has been pushed to the latest pairsamtools, but the docker-image is not up to date with it ... @golobor ?

PS not need to change anything in distiller-script itself to accommodate this +/-1 bug fix - only dependencies needs updates

**Comment by golobor** [comment]
@sergpolly , I've lost track of this one, is it solved?

**Comment by sergpolly** [comment]
Based on #115 in mirnylab/cooler that should be the case .
Even so, since we are not using pairix by default anymore...
@nandankita ? Have had any problems like this ever since?

**Comment by nandankita** [comment]
Yes, this bug was fixed and I did not encounter this issue ever since.

**Comment by sergpolly** [comment]
@nandankita close ?
